name: ROS2 test build

on:
  push:
    branches:
      - 'ros2-devel'
  
jobs:
  colcon-test-build:
    runs-on: ubuntu-22.04
    steps:
      - uses: ros-tooling/setup-ros@v0.3
        with:
          required-ros-distributions: humble
      - uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: panther_msgs
          target-ros2-distro: humble
