name: Release panther_msgs repository

on:
    pull_request: # to be removed
        branches:
            - ros2
    workflow_dispatch:
        inputs:
            release-tag:
                description: Release tag
                required: true
            release-name:
                description: Release name
                required: true
    repository_dispatch:

jobs:
    release:
        name: Release repository
        runs-on: ubuntu-22.04
        outputs:
            new_version: ${{ steps.release.outputs.new_version }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Catkin release
              id: release
              uses: husarion-ci/action-release@v0.1.4
              with:
                  bump: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.release-tag || github.event_name == 'repository_dispatch' && github.event.client_payload['release-tag'] }}
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  git_user: action-bot
                  git_email: action-bot@action-bot.com
